import { expect, test } from '@playwright/test'

test('admin grants persistent AI credits to another user and himself', async ({ page, browser }) => {
  const recipientContext = await browser.newContext()
  const recipient = await recipientContext.newPage()
  const username = `Credits-${Date.now()}`
  try {
    await recipient.goto('/')
    await recipient.getByTestId('register-toggle').click()
    await recipient.getByTestId('username-input').fill(username)
    await recipient.getByTestId('password-input').fill('A long test-only passphrase1!')
    await recipient.getByTestId('login-button').click()
    await expect(recipient.getByText(/Online/)).toBeVisible()
    await expect(recipient.getByTestId('ai-allowance')).toContainText('50/50 remaining today')
    await page.goto('/')
    await page.getByTestId('username-input').fill('CreditAdmin')
    await page.getByTestId('password-input').fill('A long test-only passphrase1!')
    await page.getByTestId('login-button').click()
    await expect(page.getByText(/Online/)).toBeVisible()
    await page.getByTestId('command-input').fill(`/ai credits add ${username} 75`)
    await page.getByTestId('command-input').press('Enter')
    await expect(page.getByTestId('transcript')).toContainText(`Added 75 AI credits to ${username}`)
    await expect(recipient.getByTestId('ai-allowance')).toContainText('75 bonus credits')
    await expect(recipient.getByTestId('ai-allowance')).toContainText('125 total available')
    await recipient.reload()
    await expect(recipient.getByText(/Online/)).toBeVisible()
    await expect(recipient.getByTestId('ai-allowance')).toContainText('75 bonus credits')
    await recipient.getByTestId('command-input').fill(`/ai credits add ${username}`)
    await recipient.getByTestId('command-input').press('Enter')
    await expect(recipient.getByTestId('transcript')).toContainText('available to admin users only')
    await page.getByTestId('command-input').fill('/ai credits add CreditAdmin')
    await page.getByTestId('command-input').press('Enter')
    await expect(page.getByTestId('ai-allowance')).toContainText('50 bonus credits')
    await expect(page.getByTestId('ai-allowance')).toContainText('100 total available')
  } finally {
    await recipientContext.close()
  }
})

test('Edric remembers a private conversation after reload', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('register-toggle').click()
  await page.getByTestId('username-input').fill(`NPC-${Date.now()}`)
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()
  await expect(page.getByText(/Online/)).toBeVisible()
  const input = page.getByTestId('command-input')
  const transcript = page.getByTestId('transcript')
  const send = async (command: string) => {
    await input.fill(command)
    await input.press('Enter')
  }
  await send('east')
  await expect(transcript).toContainText('NPCs here: Edric')
  await send('talk edric Hello from a traveler')
  await expect(transcript).toContainText('[NPC] Edric tells you privately')
  await expect(page.getByTestId('ai-allowance')).toContainText('49/50 remaining')
  await page.reload()
  await expect(page.getByText(/Online/)).toBeVisible()
  await send('talk edric remember me?')
  await expect(transcript).toContainText('Welcome back. Last time you said: Hello from a traveler')
  await expect(page.getByTestId('ai-allowance')).toContainText('48/50 remaining')
  await send('west')
  await expect(transcript).toContainText('You move west.')
  await send('talk edric hello')
  await expect(transcript).toContainText('Edric is not here.')
  await expect(page.getByTestId('ai-allowance')).toContainText('48/50 remaining')
})

test('admin can enable narration, retain it on reload, and disable it', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('username-input').fill('NarrationAdmin')
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()
  const input = page.getByTestId('command-input')
  const transcript = page.getByTestId('transcript')
  await expect(page.getByText(/Online/)).toBeVisible()
  const send = async (command: string) => {
    await input.fill(command)
    await input.press('Enter')
  }
  await send('help')
  await expect(transcript).toContainText('Admin only: /ai narration on|off')
  await send('look')
  await expect(transcript).toContainText('Town Square')
  await send('inventory')
  await expect(transcript).toContainText('Inventory: empty')
  await expect(transcript).not.toContainText('[AI narration]')
  await expect(page.getByTestId('ai-allowance')).toContainText('50/50 remaining')
  await send('/ai narration on')
  await expect(transcript).toContainText('AI narration is on for your account.')
  await send('look')
  await expect(transcript).toContainText('[AI narration]')
  await expect(page.getByTestId('ai-allowance')).toContainText('49/50 remaining')
  await page.reload()
  await expect(page.getByText(/Online/)).toBeVisible()
  await send('look')
  await expect(transcript).toContainText('[AI narration]')
  await expect(page.getByTestId('ai-allowance')).toContainText('48/50 remaining')
  const narrated = transcript.locator('.transcript-line').filter({ hasText: '[AI narration]' })
  await expect(narrated).toHaveCount(1)
  await send('/ai narration off')
  await expect(transcript).toContainText('AI narration is off for your account.')
  await send('look')
  await send('inventory')
  await expect(transcript).toContainText('Inventory: empty')
  await expect(narrated).toHaveCount(1)
  await expect(page.getByTestId('ai-allowance')).toContainText('48/50 remaining')
})

test('regular users cannot enable narration or spend allowance through /ai', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('register-toggle').click()
  await page.getByTestId('username-input').fill(`Regular-${Date.now()}`)
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()
  await expect(page.getByText(/Online/)).toBeVisible()
  await page.getByTestId('command-input').fill('help')
  await page.getByTestId('command-input').press('Enter')
  await expect(page.getByTestId('transcript')).toContainText('Slash commands:')
  await expect(page.getByTestId('transcript')).not.toContainText('Admin only:')
  await page.getByTestId('command-input').fill('/ai narration on')
  await page.getByTestId('command-input').press('Enter')
  await expect(page.getByTestId('transcript')).toContainText('The /ai command is available to admin users only.')
  await expect(page.getByTestId('ai-allowance')).toContainText('50/50 remaining')
})

test('account persists across reload, rejects wrong password, and signs out', async ({ page }) => {
  const username = `Auth-${Date.now()}`
  await page.goto('/')
  await page.getByTestId('register-toggle').click()
  await page.getByTestId('username-input').fill(username)
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()
  await expect(page.getByText(/Online/)).toBeVisible()
  await page.getByTestId('command-input').fill('north')
  await page.getByTestId('command-input').press('Enter')
  await expect(page.getByTestId('transcript')).toContainText('You move north.')
  await page.reload()
  await expect(page.getByTestId('transcript')).toContainText('You stand in the Forest.')
  await page.getByTestId('logout-button').click()
  await expect(page.getByTestId('username-input')).toBeVisible()
  await page.getByTestId('username-input').fill(username)
  await page.getByTestId('password-input').fill('This is the wrong password')
  await page.getByTestId('login-button').click()
  await expect(page.getByRole('alert')).toContainText('Invalid username or password.')
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()
  await expect(page.getByTestId('transcript')).toContainText('You stand in the Forest.')
})

test('player enters the world and moves north', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('username-input').fill('Playwright')
  await page.getByTestId('register-toggle').click()
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()

  await expect(page.getByText(/Online/)).toBeVisible()
  const transcript = page.getByTestId('transcript')
  await expect(transcript).toContainText(/You stand in the (Town Square|Forest)\./)

  if ((await transcript.textContent())?.includes('Forest')) {
    await page.getByTestId('command-input').fill('south')
    await page.getByTestId('command-input').press('Enter')
    await expect(transcript).toContainText('Town Square')
  }

  await page.getByTestId('command-input').fill('north')
  await page.getByTestId('command-input').press('Enter')

  await expect(transcript).toContainText('You move north.')
  await expect(transcript).toContainText('Forest')
})

test('natural commands use interpretation while narration defaults off', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('username-input').fill(`NaturalPlaywright-${Date.now()}`)
  await page.getByTestId('register-toggle').click()
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()

  const terminal = page.getByTestId('terminal')
  const transcript = page.getByTestId('transcript')
  const commandInput = page.getByTestId('command-input')
  await expect(page.getByText(/Online/)).toBeVisible()

  await commandInput.fill('look')
  await commandInput.press('Enter')
  await expect(terminal).toHaveAttribute('data-command-source', 'classic')
  await expect(page.getByTestId('ai-allowance')).toContainText('50/50 remaining')

  await commandInput.fill('walk toward the docks')
  await commandInput.press('Enter')
  await expect(transcript).toContainText('You move south.')
  await expect(transcript).toContainText('Docks')
  await expect(page.getByTestId('ai-allowance')).toContainText('49/50 remaining')
  await expect(page.getByTestId('current-room')).toHaveText('Docks')
  await expect(terminal).toHaveAttribute('data-command-source', 'ai')

  await commandInput.fill('perform an undocumented action')
  await commandInput.press('Enter')
  await expect(transcript).toContainText(
    "I couldn't interpret that command. Try 'help' for available commands.",
  )
  await expect(page.getByTestId('ai-allowance')).toContainText('48/50 remaining')
  await expect(transcript).not.toContainText('[AI narration]')
  await expect(terminal).toHaveAttribute('data-command-source', 'ai')
})

test('player can toggle safe debug diagnostics in the transcript', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('username-input').fill(`DebugPlaywright-${Date.now()}`)
  await page.getByTestId('register-toggle').click()
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()

  const terminal = page.getByTestId('terminal')
  const transcript = page.getByTestId('transcript')
  const commandInput = page.getByTestId('command-input')
  await expect(page.getByText(/Online/)).toBeVisible()

  await commandInput.fill('/debug on')
  await commandInput.press('Enter')
  await expect(terminal).toHaveAttribute('data-debug', 'on')

  await commandInput.fill('look')
  await commandInput.press('Enter')
  await expect(transcript).toContainText(
    '[DEBUG] type=game_output success=true room_id=town_square command_source=classic',
  )

  await commandInput.fill('/debug off')
  await commandInput.press('Enter')
  await expect(terminal).toHaveAttribute('data-debug', 'off')
})

test('a connected username cannot be used by another player', async ({ browser }) => {
  const firstPage = await browser.newPage()
  const secondPage = await browser.newPage()

  await firstPage.goto('/')
  await firstPage.getByTestId('username-input').fill('UniquePlaywright')
  await firstPage.getByTestId('register-toggle').click()
  await firstPage.getByTestId('password-input').fill('A long test-only passphrase1!')
  await firstPage.getByTestId('login-button').click()
  await expect(firstPage.getByText(/Online/)).toBeVisible()

  await secondPage.goto('/')
  await secondPage.getByTestId('username-input').fill(' uniqueplaywright ')
  await secondPage.getByTestId('password-input').fill('A long test-only passphrase1!')
  await secondPage.getByTestId('login-button').click()

  await expect(secondPage.getByTestId('transcript')).toContainText(
    '[ERROR] That username is already connected.',
  )
})

test('player can open and close a persistent item', async ({ page }) => {
  await page.goto('/')
  await page.getByTestId('username-input').fill('ItemPlaywright')
  await page.getByTestId('register-toggle').click()
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()

  const transcript = page.getByTestId('transcript')
  await expect(transcript).toContainText(/You stand in the (Town Square|Forest)\./)
  const commandInput = page.getByTestId('command-input')
  const send = async (command: string, expected: string | RegExp) => {
    const previousLines = await transcript.locator('.transcript-line').count()
    await expect(commandInput).toBeEnabled()
    // Pace keyboard input below the server's command limit and assert a fresh reply.
    await commandInput.pressSequentially(command, { delay: 50 })
    await commandInput.press('Enter')
    await expect(transcript.locator('.transcript-line').nth(previousLines + 1)).toContainText(expected)
    await expect(transcript).not.toContainText('[ERROR]')
    await expect(commandInput).toBeEnabled()
  }

  if ((await transcript.textContent())?.includes('Forest')) {
    await send('south', 'You move south.')
  }
  await send('close chest', /The chest is already closed|You close the chest/)
  await send('open chest', 'You open the chest.')
  await send('take torch', 'You take the torch.')
  await expect(page.getByTestId('inventory-panel').getByRole('listitem')).toHaveText('torch')
  await page.screenshot({ path: 'test-results/ui-desktop.png' })
  await page.getByRole('button', { name: 'Inventory', exact: true }).focus()
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('inventory-panel')).toHaveCount(0)
  await page.keyboard.press('Enter')
  await expect(page.getByTestId('inventory-panel')).toBeVisible()
  await page.getByRole('button', { name: 'Inventory', exact: true }).click()
  await expect(page.getByTestId('inventory-panel')).toHaveCount(0)
  await page.reload()
  await expect(page.getByText(/Online/)).toBeVisible()
  await expect(page.getByTestId('inventory-panel')).toHaveCount(0)
  await commandInput.fill('/panel inventory show')
  await commandInput.press('Enter')
  await expect(page.getByTestId('inventory-panel').getByRole('listitem')).toHaveText('torch')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(commandInput).toBeInViewport()
  await expect(page.getByTestId('inventory-panel')).toBeInViewport()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/ui-mobile.png' })
  await send('put torch in chest', 'You put the torch in the chest.')
  await expect(page.getByTestId('inventory-panel')).toContainText('Your inventory is empty.')
  await send('look in chest', 'The chest contains: torch.')
  await send('take torch from chest', 'You take the torch from the chest.')
  await send('use torch', 'The torch casts a steady pool of light.')
  await send('look', 'Torchlight reaches farther.')
  await send('put torch in chest', 'You must extinguish the torch before putting it in the chest.')
  await send('put out torch', 'You extinguish the torch.')
  await send('use torch', 'The torch casts a steady pool of light.')
  await send('drop torch', 'You drop the torch. It goes out.')
})
