import { expect, test } from '@playwright/test'

test('visited floors stay ghosted, compact, and readable around the current neighborhood', async ({ page }) => {
  await page.setViewportSize({ width: 1920, height: 1080 })
  await page.goto('/')
  await page.getByTestId('username-input').fill('MapExplorer')
  await page.getByTestId('password-input').fill('A long test-only passphrase1!')
  await page.getByTestId('login-button').click()
  const panel = page.getByTestId('map-panel')
  await expect(panel.getByRole('button', { name: 'Cedar Hall, you are here' })).toBeVisible()
  await panel.getByRole('button', { name: 'Expand map' }).click()
  await expect(panel.locator('[data-level]')).toHaveCount(5)
  await expect(panel.locator('[data-level="1"]')).toHaveCSS('opacity', '0.3')
  await expect(panel.locator('[data-level="2"]')).toHaveCSS('opacity', '0.15')
  await expect(panel.locator('[data-level="-1"]')).toHaveCSS('opacity', '0.3')
  await expect(panel.locator('[data-level="-2"]')).toHaveCSS('opacity', '0.15')
  await expect(panel.getByRole('button', { name: /Roof|Deep Cave|Unvisited Vault/ })).toHaveCount(0)
  await expect(panel.getByRole('button', { name: 'Library', exact: true }).getByRole('img', { name: 'Down exits' })).toBeVisible()
  const hall = panel.locator('[data-room="map_hall"]')
  const layout = await hall.getAttribute('transform')
  const fontSize = () => hall.locator('.map-label text').first().evaluate(el => {
    const svgText = el as SVGGraphicsElement
    return parseFloat(getComputedStyle(el).fontSize) * svgText.getScreenCTM()!.a
  })
  const initialFont = await fontSize()
  await page.screenshot({ path: 'test-results/map-levels-desktop.png' })
  await panel.getByRole('button', { name: 'Zoom out' }).click()
  expect(await fontSize()).toBeCloseTo(initialFont, 1)
  await panel.getByRole('button', { name: 'Nearby levels' }).click()
  await expect(panel.locator('[data-level]')).toHaveCount(1)
  await expect(hall).toHaveAttribute('transform', layout!)
  await panel.getByRole('button', { name: 'Nearby levels' }).click()
  const command = page.getByTestId('command-input')
  await command.fill('up')
  await command.press('Enter')
  await expect(panel.locator('[data-level="0"] [data-room="map_landing"]')).toBeVisible()
  await expect(panel.locator('[data-level="-1"] [data-room="map_hall"]')).toBeVisible()
  await expect(panel.locator('[data-level="2"] [data-room="map_roof"]')).toBeAttached()
  await expect(panel.locator('[data-room="map_tunnel"]')).toHaveCount(0)
  await panel.getByRole('button', { name: 'Center on me' }).click()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByTestId('command-input')).toBeVisible()
  await expect(panel.getByRole('button', { name: 'Landing, you are here' })).toBeInViewport({ ratio: 1 })
  expect((await panel.boundingBox())!.height).toBeLessThanOrEqual(844 * 0.4 + 1)
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/map-levels-mobile.png' })
})
